### PR TITLE
Set environment variables correctly for `powershell`

### PR DESCRIPTION
**Pull request by Boegie19**
fixes the issue with after failing to find path on windows

### CODE REVIEW

**Comment by ok-nick** [comment]
We discussed this in discord, but I just wanted to mention it here.

[In your CI](https://github.com/Boegie19/rojo/runs/7857487757?check_suite_focus=true), after running `setup-aftman`, the installed executable is not being recognized on Windows. The CI running on this repo works fine, even on Windows. Obviously, there seems to be an issue, but I am not sure we fully understand it. I don't want to merge this until we know where the problem originates and we are confident that this is the correct way to address it.

**Comment by Boegie19** [comment]
Found the issue github defaults to powershell if you force it to use bash then it will work.

**Comment by ok-nick** [comment]
It was suggested that the issue may be due to `powershell` not recognizing the Unix-style path being added to `PATH`. Instead, maybe we can fix the file path before adding it to the `PATH` env variable?

**Comment by ok-nick** [comment]
It's probably easier to just set the env variables on each respective shell as done here.

Could you create two separate steps for setting the environment variable (one using bash and one using powershell on Linux and Windows) instead of using the whole install procedure.

**Comment by ok-nick** [comment]
Looks good, the failure was due to github rate limit, still waiting for the `aftman` PR to go through.

**Pull request merged**
